In [16]:
import numpy as np

xs = np.linspace(0,40,3)
ys = np.linspace(0,60,3)



In [17]:
xs,ys = np.meshgrid(xs,ys)

In [18]:
xs.ravel()

array([ 0., 20., 40.,  0., 20., 40.,  0., 20., 40.])

In [19]:
ys.ravel()

array([ 0.,  0.,  0., 30., 30., 30., 60., 60., 60.])

In [20]:
ys

array([[ 0.,  0.,  0.],
       [30., 30., 30.],
       [60., 60., 60.]])

In [21]:
xs

array([[ 0., 20., 40.],
       [ 0., 20., 40.],
       [ 0., 20., 40.]])

In [22]:
xy = np.column_stack((xs.ravel(), ys.ravel()))

In [23]:
xy

array([[ 0.,  0.],
       [20.,  0.],
       [40.,  0.],
       [ 0., 30.],
       [20., 30.],
       [40., 30.],
       [ 0., 60.],
       [20., 60.],
       [40., 60.]])